# Generated by Django 3.1.2 on 2020-11-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=10)),
                ('irum', models.CharField(max_length=20)),
                ('juso', models.CharField(max_length=100)),
                ('nai', models.IntegerField()),
            ],
        ),
    ]
