# Generated by Django 3.1.2 on 2020-11-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sangdata',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('sang', models.CharField(blank=True, max_length=20, null=True)),
                ('su', models.IntegerField(blank=True, null=True)),
                ('dan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sangdata',
                'managed': False,
            },
        ),
    ]
